# Generated by Django 2.2.4 on 2019-09-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='compras',
            name='preco_max',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='compras',
            name='quant_mes',
            field=models.FloatField(),
        ),
    ]
