# Generated by Django 2.2.4 on 2019-09-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_compras', '0002_auto_20190912_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='preco_max',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
