# Generated by Django 2.2.4 on 2019-09-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_compras', '0003_auto_20190912_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='compras',
            name='quant_mes',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
